# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190419_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='n_casualleave',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='user',
            name='u_casualleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
