# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-21 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20190421_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='a_Earnleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_casualleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_commutingleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_dutyleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_halfleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_maternityleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_paternityleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_sickleave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='a_specialleave',
            field=models.IntegerField(default=0),
        ),
    ]
