# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-04-21 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Faculty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaves',
            name='status',
            field=models.IntegerField(default=3),
        ),
    ]
